In [1]:
import numpy as np
def load_data(filename):
    data = []
    labels = []
    fr = open(filename)
    for line in fr.readlines():
        line_arr = line.strip().split("\t")
        data.append([float(line_arr[0]), float(line_arr[1])])
        labels.append(float(line_arr[-1]))
    return data, labels


In [10]:
data,labels=load_data("d:/PycharmProjects/机器学习实战/SVM/testSet.txt")

In [12]:
data1=np.mat(data)
data1

matrix([[ 3.542485e+00,  1.977398e+00],
        [ 3.018896e+00,  2.556416e+00],
        [ 7.551510e+00, -1.580030e+00],
        [ 2.114999e+00, -4.466000e-03],
        [ 8.127113e+00,  1.274372e+00],
        [ 7.108772e+00, -9.869060e-01],
        [ 8.610639e+00,  2.046708e+00],
        [ 2.326297e+00,  2.652130e-01],
        [ 3.634009e+00,  1.730537e+00],
        [ 3.413670e-01, -8.949980e-01],
        [ 3.125951e+00,  2.932510e-01],
        [ 2.123252e+00, -7.835630e-01],
        [ 8.878350e-01, -2.797792e+00],
        [ 7.139979e+00, -2.329896e+00],
        [ 1.696414e+00, -1.212496e+00],
        [ 8.117032e+00,  6.234930e-01],
        [ 8.497162e+00, -2.666490e-01],
        [ 4.658191e+00,  3.507396e+00],
        [ 8.197181e+00,  1.545132e+00],
        [ 1.208047e+00,  2.131000e-01],
        [ 1.928486e+00, -3.218700e-01],
        [ 2.175808e+00, -1.452700e-02],
        [ 7.886608e+00,  4.617550e-01],
        [ 3.223038e+00, -5.523920e-01],
        [ 3.628502e+00,  2.190585e+00],


In [14]:
np.shape(data1)

(100, 2)

In [9]:
np.shape(np.mat(labels))

(1, 100)

In [16]:
data_arr=np.array(data)
np.shape(data_arr)
dat=np.transpose(data_arr)
dat

array([[ 3.542485e+00,  3.018896e+00,  7.551510e+00,  2.114999e+00,
         8.127113e+00,  7.108772e+00,  8.610639e+00,  2.326297e+00,
         3.634009e+00,  3.413670e-01,  3.125951e+00,  2.123252e+00,
         8.878350e-01,  7.139979e+00,  1.696414e+00,  8.117032e+00,
         8.497162e+00,  4.658191e+00,  8.197181e+00,  1.208047e+00,
         1.928486e+00,  2.175808e+00,  7.886608e+00,  3.223038e+00,
         3.628502e+00,  7.407860e+00,  7.286357e+00,  2.301095e+00,
        -2.325420e-01,  3.457096e+00,  3.023938e+00,  8.015003e+00,
         8.991748e+00,  7.916831e+00,  7.616862e+00,  2.450939e+00,
         7.270337e+00,  1.749721e+00,  1.803111e+00,  8.804461e+00,
         1.231257e+00,  2.074915e+00, -7.430360e-01,  3.536555e+00,
         8.410143e+00,  7.382988e+00,  6.960661e+00,  8.234460e+00,
         8.168618e+00,  1.534187e+00,  9.229518e+00,  7.886242e+00,
         2.893743e+00,  1.870457e+00,  5.286862e+00,  6.080573e+00,
         2.544314e+00,  6.016004e+00,  9.263100e

In [17]:
np.shape(labels)

(100,)

In [19]:
label_mat=np.mat(labels).transpose()

alpha=np.zeros((100,1))
res=np.multiply(alpha,label_mat)
res
np.shape(res)

(100, 1)

In [20]:
np.shape(label_mat)



(100, 1)

In [21]:
np.shape(alpha)

(100, 1)

In [22]:
type(alpha)
type(label_mat)


numpy.matrix

In [23]:
alpha


array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [37]:
label_arr=np.array(labels)

In [38]:
la=label_arr.reshape(1,-1)
la

array([[-1., -1.,  1., -1.,  1.,  1.,  1., -1., -1., -1., -1., -1., -1.,
         1., -1.,  1.,  1., -1.,  1., -1., -1., -1.,  1., -1., -1.,  1.,
         1., -1., -1., -1., -1.,  1.,  1.,  1.,  1., -1.,  1., -1., -1.,
         1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,
        -1., -1.,  1.,  1., -1.,  1., -1., -1., -1., -1.,  1., -1.,  1.,
        -1., -1.,  1.,  1.,  1., -1.,  1.,  1., -1., -1.,  1., -1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1., -1.,  1., -1.,  1.,
         1.,  1., -1., -1., -1., -1., -1., -1., -1.]])

In [39]:
lat=la.T
lat

array([[-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
      

In [41]:
lnt=np.tile(lat,(1,2))
lnt

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [-1., -1.],
       [ 1.,  1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [-1., -1.],
       [ 1.,  1.],
       [-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [-1.,

In [42]:
data_arr=np.array(data)
data_arr

array([[ 3.542485e+00,  1.977398e+00],
       [ 3.018896e+00,  2.556416e+00],
       [ 7.551510e+00, -1.580030e+00],
       [ 2.114999e+00, -4.466000e-03],
       [ 8.127113e+00,  1.274372e+00],
       [ 7.108772e+00, -9.869060e-01],
       [ 8.610639e+00,  2.046708e+00],
       [ 2.326297e+00,  2.652130e-01],
       [ 3.634009e+00,  1.730537e+00],
       [ 3.413670e-01, -8.949980e-01],
       [ 3.125951e+00,  2.932510e-01],
       [ 2.123252e+00, -7.835630e-01],
       [ 8.878350e-01, -2.797792e+00],
       [ 7.139979e+00, -2.329896e+00],
       [ 1.696414e+00, -1.212496e+00],
       [ 8.117032e+00,  6.234930e-01],
       [ 8.497162e+00, -2.666490e-01],
       [ 4.658191e+00,  3.507396e+00],
       [ 8.197181e+00,  1.545132e+00],
       [ 1.208047e+00,  2.131000e-01],
       [ 1.928486e+00, -3.218700e-01],
       [ 2.175808e+00, -1.452700e-02],
       [ 7.886608e+00,  4.617550e-01],
       [ 3.223038e+00, -5.523920e-01],
       [ 3.628502e+00,  2.190585e+00],
       [ 7.407860e+00, -1

In [43]:
np.dot(lnt,data)



ValueError: shapes (100,2) and (100,2) not aligned: 2 (dim 1) != 100 (dim 0)